[package]
name = "template"
version = "0.1.0"

[dependencies]
conrod = { version = "0.61", features = ["glium", "winit"] }
conrod_derive = "*"
winit = "*"
glium = "*"
ron = "0.4.0"
serde = "*"
find_folder = "0.3.0"
rustfft = "*"
audioengine = { path = "./audioengine" }
